"""Write the runtime's tool descriptions to prompts/tool_descriptions.yaml.

The multi-surface optimizer needs the agent's CURRENT tool descriptions as its
starting point (the ``base`` of ``ToolDescriptionFormula``). They live in the
``@tool`` docstrings of this runtime's environment, so this script reads those
source files, builds each tool spec exactly the way ``strands`` does, and writes the
descriptions out. Re-run it whenever a tool docstring changes::

    python examples/appworld/appworld_runtime/dump_tool_descriptions.py

Reads the source with ``ast`` rather than importing the environment, so it needs
neither the benchmark's dependencies nor a running server -- only ``strands``.
"""

import ast
import os
import sys

from strands_harness_optimizer.formulas.tool_description_formula import dump_yaml

HERE = os.path.dirname(os.path.abspath(__file__))
# Files holding the @tool-decorated functions the agent is given.
TOOL_SOURCES = [os.path.join(HERE, "dataset", "appworld_strands_tool.py")]
OUT = os.path.join(HERE, "prompts", "tool_descriptions.yaml")


def _is_tool_decorator(node: ast.expr) -> bool:
    return (isinstance(node, ast.Name) and node.id == "tool") or (
        isinstance(node, ast.Attribute) and node.attr == "tool"
    )


def _describe(fn: ast.FunctionDef) -> str:
    """Rebuild the function as a stub and let ``strands.tool`` parse its docstring."""
    from strands import tool

    args = ", ".join(
        a.arg + (": str" if a.annotation is None else ": " + ast.unparse(a.annotation))
        for a in fn.args.args
        if a.arg != "self"
    )
    doc = ast.get_docstring(fn, clean=False) or ""
    src = f"def {fn.name}({args}) -> str:\n    {doc!r}\n    return ''\n"
    ns: dict = {}
    exec(src, {"__builtins__": __builtins__}, ns)  # noqa: S102 - our own source, rebuilt
    return str(tool(ns[fn.name]).tool_spec["description"])


def collect() -> dict[str, str]:
    out: dict[str, str] = {}
    for path in TOOL_SOURCES:
        with open(path) as f:
            tree = ast.parse(f.read(), filename=path)
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and any(
                _is_tool_decorator(d) for d in node.decorator_list
            ):
                out[node.name] = _describe(node)
    return out


def main() -> int:
    descriptions = collect()
    if not descriptions:
        print("no @tool functions found", file=sys.stderr)
        return 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(
            "# The runtime's tool descriptions, as the agent sees them. Generated by\n"
            "# dump_tool_descriptions.py from the @tool docstrings; the multi-surface\n"
            "# optimizer starts from this map and ships only the entries it edits.\n"
        )
        f.write(dump_yaml(descriptions))
    print(f"wrote {len(descriptions)} tool description(s) -> {OUT}: {sorted(descriptions)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
